### PR TITLE
Upgrade Apollo to version 3.0.2 and fix crash when adding product without image to cart

### PR DESCRIPTION
**Pull request by w3bdesign**
- Minimize dependency on external packages by replacing Lodash isEmpty with custom function 
- Updated all NPM packages
- Fix site crashing if we add a product without an image to cart
- Upgraded Apollo from v 2.6 to 3.0.2
- Replaced Ruby Markdown in README with Javascript Markdown
- Fix incorrect country code for India (was ID for Indonesia)
- Fix spelling error in OrderSuccess 
- Implemented Nprogress with Next Router to display a loading indicator for visual feedback

TODO:

Take a look at reintroducing FragmentMatcher. 
See https://github.com/apollographql/apollo-client/pull/5073 and https://www.apollographql.com/docs/react/data/fragments/#defining-possibletypes-manually

### CODE REVIEW

**Comment by w3bdesign** [comment]
Also I ran Prettier as it makes the code look better :+1:

**Comment by w3bdesign** [comment]
Updated all non-Apollo NPM packages

**Comment by imranhsayed** [comment]
@w3bdesign 
Thank you for the contribution.
I see that when you add a product ot the cart, and go the the cart page. The cart page does not reflect any changes.
Can you please test it at your end ?

image

**Comment by w3bdesign** [comment]
@imranhsayed 

Is the WooCommerce installation local or remote? 

I found out that if I use Xampp, the update takes a minute or two, but is really fast on an online installation.

I recommend that you experiment with a different WooCommerce installation and see if that may be the reason.

**Comment by imranhsayed** [comment]
@w3bdesign 
I had tested it online as well. Can you try deploying your branch on netlify or vercel and test it once.
Could you also raise a fresh PR please, as there had been changes after hat ?

**Pull request merged**
